export { default as Dashboard } from "./Dashboard/dashboard";
export { default as Home } from "./Home/home";
export { default as LandingPage } from "./LandingPage/landing";
export { default as Login } from "./LoginPage/login";
export { default as Posting } from "./PostingPage/posting";
export { default as Profile } from "./ProfilePage/profile";
export { default as Register } from "./RegisterPage/register";
export { default as Post } from "./PostPage/post";
export { default as Footer } from "./Footer/footer";
